### ISSUE TITLE
 Error: Microsoft.JSInterop.JSException: Could not find 'Skclusive' in 'window'.

### ISSUE THREAD

**Issue by einsisdev** [skclusive/Skclusive.Blazor.Samples#9]
I always get this error when I open the server example in a new browser tab and the SidebarContent menu is not displayed and to fix it you need to refresh the page.

2020-05-04T15:44:58.459Z] Error: Microsoft.JSInterop.JSException: Could not find 'Skclusive' in 'window'.
Error: Could not find 'Skclusive' in 'window'.
    at https://localhost:44394/_framework/blazor.server.js:8:30748
    at Array.forEach (<anonymous>)
    at p (https://localhost:44394/_framework/blazor.server.js:8:30709)
    at https://localhost:44394/_framework/blazor.server.js:8:31416
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44394/_framework/blazor.server.js:8:31390)
    at https://localhost:44394/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44394/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (https://localhost:44394/_framework/blazor.server.js:1:17165)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Skclusive.Script.DomHelpers.DomHelpers.MoveContentAsync(Nullable`1 source, Nullable`1 target, Nullable`1 targetBody)
   at Skclusive.Material.Core.Portal.OnAfterRenderAsync()
   at Skclusive.Core.Component.RenderComponentBase.OnAfterRenderAsync(Boolean firstRender)
   at Skclusive.Core.Component.DisposableComponentBase.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by skclusive** [comment]
thanks for reporting. this issue has been fixed in develop branch. closing the issue
